spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  web:
    locale: pt_BR
    hiddenmethod:
      filter:
        enabled: true
  banner:
    charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chama_sindico
    username: root
    password: mysql
    hikari:
      validation-timeout: 300000
  mail:
    host: smtp.gmail.com
    port: 587
    username: chamasindico.contato@gmail.com
    password:
    properties.mail.smtp:
          auth: true
          starttls.enable: true

# logs the SQL statements
logging:
  level:
    org:
      hibernate:
        sql: debug
        type: trace

server:
  servlet:
    context-path: /chamasindico
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/json,text/javascript
    min-response-size: 1024
app:
  jwtSecret: 5e21678e6928941ed88184275d052a343a68e1de
  jwtExpirationInMs: 604800000
